image:
  repository: ghcr.io/tiesmaster/overdue-book-reporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

cronSpec:
  schedule: "0 1 * * *"
  # successfulJobsHistoryLimit: 7
  # failedJobsHistoryLimit: 30

# The config block contains the configuration of the application. See
# [.env.sample](https://github.com/tiesmaster/overdue-book-reporter/blob/main/.env.sample)
# for all supported configuration settings.

config:
  libraryLoginCredentials: {}
    # username: AzureDiamond
    # password: hunter2

  emailSettings:
    from: {}
      # name: OverdueBookReporter
      # address: john@gmail.com
    to: {}
      # name: John
      # address: john@gmail.com
    mailServer: {}
      # host: smtp.gmail.com
      # port: 465
      # useSsl: true
      # username:
      # password: