apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "overdue-book-reporter.fullname" . }}
{{- with .Values.config }}
data:
  LIBRARYLOGINCREDENTIALS__USERNAME: {{ .libraryLoginCredentials.username | quote }}
  EMAILSETTINGS__FROM__NAME: {{ .emailSettings.from.name | quote }}
  EMAILSETTINGS__FROM__ADDRESS: {{ .emailSettings.from.address | quote }}
  EMAILSETTINGS__TO__NAME: {{ .emailSettings.to.name | quote }}
  EMAILSETTINGS__TO__ADDRESS: {{ .emailSettings.to.address | quote }}
  EMAILSETTINGS__MAILSERVER__HOST: {{ .emailSettings.mailServer.host | quote }}
  EMAILSETTINGS__MAILSERVER__PORT: {{ .emailSettings.mailServer.port | quote }}
  EMAILSETTINGS__MAILSERVER__USESSL: {{ .emailSettings.mailServer.useSsl | quote }}
  EMAILSETTINGS__MAILSERVER__USERNAME: {{ .emailSettings.mailServer.username | quote }}
{{- end }}