apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "overdue-book-reporter.fullname" . }}
spec:
  {{- with .Values.cronSpec }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "overdue-book-reporter.selectorLabels" . | nindent 6 }}
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "overdue-book-reporter.labels" . | nindent 12 }}
            {{- with .Values.podLabels }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          restartPolicy: Never
          containers:
          - name: overdue-book-reporter
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (print "v" .Chart.AppVersion) }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            envFrom:
            - configMapRef:
                name: {{ include "overdue-book-reporter.fullname" . }}
            - secretRef:
                name: {{ include "overdue-book-reporter.fullname" . }}
