apiVersion: v1
kind: Secret
metadata:
  name: {{ include "overdue-book-reporter.fullname" . }}
{{- with .Values.config }}
stringData:
  LIBRARYROTTERDAMCLIENT__LOGIN__PASSWORD: {{ .libraryRotterdamClient.login.password | quote }}
  EMAILSETTINGS__MAILSERVER__PASSWORD: {{ .emailSettings.mailServer.password | quote }}
{{- end }}