apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ping_exporter.fullname" . }}
{{- with .Values.config }}
data:
  LIBRARYLOGINCREDENTIALS__PASSWORD: {{ .libraryLoginCredentials.password | quote }}
  EMAILSETTINGS__MAILSERVER__PASSWORD: {{ .emailSettings.mailServer.password | quote }}
{{- end }}